name: "1.0.8-$(Date:yyyyMMdd).$(Rev:r)-$(Build.SourceBranchName)"

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables: 
  extensionVersion: 1.0.8

resources:
  repositories:
  - repository: TestRepo
    type: git
    name: Dimaros/Dimaros.CRM.SolutionExtractor.Test

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: "Build"
    steps:
      - checkout: self
      - task: TfxInstaller@4
        displayName: 'Use Node CLI for Azure DevOps'
        inputs:
          version: '0.x'
          checkLatest: true
      - task: PackageAzureDevOpsExtension@4
        displayName: 'Package Extension'
        name: 'packageStep'
        inputs:
          rootFolder: '$(Build.SourcesDirectory)'
          outputPath: '$(Build.ArtifactStagingDirectory)'
          updateTasksVersion: true
          extensionPricing: 'free'
          extensionVersion: '$(extensionVersion)'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish vsix'
        inputs:
          publishLocation: pipeline
          targetPath: '$(packageStep.Extension.OutputPath)'
          artifact: 'vsix'
        condition: succeededOrFailed()

- stage: 'Test'
  jobs:
  - job: IntegrationTest
    displayName: "Integration Test"
    variables:
      testScriptPath: "solutionExtractor/tests/ExtractSolutionAndCreatePR.IntegrationTest.ps1"
    steps:
    - checkout: self
    - checkout: TestRepo
    - task: PowerShell@2
      inputs:
        filePath: "$(Build.SourcesDirectory)/crm-solution-extractor/$(testScriptPath)"
        arguments: >
          -repositoryRoot "$(Build.SourcesDirectory)/TestRepo"
          -newBranchName "solution-extract-$(Build.BuildNumber)"
          -connectionString $(crmConnection)
      env:
        System_AccessToken: $(System.AccessToken)
  - job: waitForValidation  
    displayName: "Wait for validation"
    pool: server
    dependsOn: 'IntegrationTest'
    timeoutInMinutes: "1440" # job times out in 24 hours
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: "D365SolutionExtractor-Support@dimaros.nl"
        instructions: |
          - Check if PR is created in AzureDevOps Dimaros.CRM.SolutionExtractor.Test repository.

- stage: Publish
  displayName: 'Publish to Marketplace'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: SolutionExtractorDeployment
    environment: solution-extractor
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: TfxInstaller@4
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: '0.x'
              checkLatest: true

          - task: PublishAzureDevOpsExtension@3
            name: 'publishProd'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Visual Studio Marketplace Service Connection'
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/vsix/*.vsix'

          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'DimarosBV'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(extensionVersion)'
              title: 'v$(extensionVersion)'
              releaseNotesSource: 'inline'
              assets: '$(publishProd.Extension.OutputPath)*'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
