name: '1.0$(Rev:.r)'

trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: "Build"
    steps:
      - task: TfxInstaller@4
        displayName: 'Use Node CLI for Azure DevOps'
        inputs:
          version: '0.x'
          checkLatest: true
      - task: PackageAzureDevOpsExtension@4
        displayName: 'Package Extension'
        name: 'packageStep'
        inputs:
          rootFolder: '$(Build.SourcesDirectory)'
          outputPath: '$(Build.ArtifactStagingDirectory)'
          updateTasksVersion: true
          extensionPricing: 'free'
          extensionVersion: '$(Build.BuildNumber)'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish vsix'
        inputs:
          publishLocation: pipeline
          targetPath: '$(packageStep.Extension.OutputPath)'
          artifact: 'vsix'
        condition: succeededOrFailed()
      
- stage: Publish
  displayName: 'Publish to Marketplace'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: 'Build'
  jobs:
  - deployment: SolutionExtractorDeployment
    environment: solution-extractor
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: TfxInstaller@4
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: '0.x'
              checkLatest: true

          - task: PublishAzureDevOpsExtension@3
            name: 'publishProd'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Visual Studio Marketplace Service Connection'
              fileType: 'vsix'
              vsixFile: '$(Build.ArtifactStagingDirectory)/vsix/*.vsix'

          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'Dimaros'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(Build.BuildNumber)'
              title: 'v$(Build.BuildNumber)'
              releaseNotesSource: 'inline'
              assets: '$(publishProd.Extension.OutputPath)*'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
