name: "1.0.8-$(Date:yyyyMMdd).$(Rev:r)-$(Build.SourceBranchName)"

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables: 
  extensionVersion: 1.0.8

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: "Build"
    steps:
      - checkout: self
      - task: TfxInstaller@4
        displayName: 'Use Node CLI for Azure DevOps'
        inputs:
          version: '0.x'
          checkLatest: true
      - task: PackageAzureDevOpsExtension@4
        displayName: 'Package Extension'
        name: 'packageStep'
        inputs:
          rootFolder: '$(Build.SourcesDirectory)'
          outputPath: '$(Build.ArtifactStagingDirectory)'
          updateTasksVersion: true
          extensionPricing: 'free'
          extensionVersion: '$(extensionVersion)'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish vsix'
        inputs:
          publishLocation: pipeline
          targetPath: '$(packageStep.Extension.OutputPath)'
          artifact: 'vsix'
        condition: succeededOrFailed()

- stage: PublishDev
  displayName: 'Publish Dev'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Publish
    displayName: "Publish to Marketplace"
    steps:
    - checkout: none
    
    - download: current
      artifact: vsix

    - task: TfxInstaller@4
      displayName: 'Use Node CLI for Azure DevOps'
      inputs:
        version: '0.x'
        checkLatest: true

    - task: PublishAzureDevOpsExtension@4
      name: 'PublishExtension'
      displayName: 'Publish extension'
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Visual Studio Marketplace Service Connection'
        fileType: 'vsix'
        vsixFile: '$(Pipeline.Workspace)/vsix/*.vsix'
        extensionId: 'd365-solution-extractor-dev'
        extensionName: 'D365 Solution Extractor Dev'
        extensionVersion: '$(extensionVersion)'

- stage: Test
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: waitForValidation  
    displayName: "Wait for validation"
    pool: server
    timeoutInMinutes: "1440" # job times out in 24 hours
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: "D365SolutionExtractor-Support@dimaros.nl"
        instructions: |
          - Check if PR is created in AzureDevOps Dimaros.CRM.SolutionExtractor.Test repository.

- stage: PublishProd
  displayName: 'Publish Prod'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: SolutionExtractorDeployment
    environment: solution-extractor
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: TfxInstaller@4
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: '0.x'
              checkLatest: true

          - task: PublishAzureDevOpsExtension@3
            name: 'publishProd'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Visual Studio Marketplace Service Connection'
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/vsix/*.vsix'

          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'DimarosBV'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(extensionVersion)'
              title: 'v$(extensionVersion)'
              releaseNotesSource: 'inline'
              assets: '$(publishProd.Extension.OutputPath)*'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
