trigger:
- none

pool:
  vmImage: windows-2019

steps:

- checkout: self
  persistCredentials: true

- task: D365SolutionExtractor@1
  inputs:
    newBranchName: 'solution-extract-$(Build.BuildNumber)'
    connectionString: '$(dataverseConnectionString)'
    solutionName: 'MyAwesomeSolution'
  env:
    System_AccessToken: $(System.AccessToken) // PAT of a build-in service user
